### ISSUE TITLE
images not working

### ISSUE THREAD

**Issue by DurveshKumarPal** [DurveshKumarPal/personal-portfolio-website#1]

**Comment by Tathagata-42** [comment]
@DurveshKumarPal Have you solved it ? Should I help ?

**Comment by DurveshKumarPal** [comment]
why not

**Comment by DurveshKumarPal** [comment]
I'll assign to you.

**Comment by DurveshKumarPal** [comment]
I'll assign it to you.

**Comment by leonardsangoroh** [comment]
@DurveshKumarPal If you haven't sorted the issue out kindly let me assist

**Comment by DurveshKumarPal** [comment]
@leonardsangoroh Can you solve the urgent?

**Comment by leonardsangoroh** [comment]
@DurveshKumarPal Yes, I can solve it within 12 hours.

Just assign the task to me, and I'll work on it within the given time frame

**Comment by DurveshKumarPal** [comment]
Do it @leonardsangoroh

**Comment by leonardsangoroh** [comment]
@DurveshKumarPal On it

**Comment by leonardsangoroh** [comment]
Kindly look at the pull request I have created and merge it to the main

**Comment by DurveshKumarPal** [comment]
Thanks @leonardsangoroh
